version: '3.9'

services:

  postgres:
    container_name: todolist
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_nw
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge